package com.example.to_dolist.database;

import androidx.annotation.NonNull;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.util.Date;

@Entity(tableName = "todos")
/**
 * Represents a task in the to-do list.
 * Each task has a unique ID, a description, a due date, and a completion status.
 *
 * @param id    Unique identifier for the task (auto-generated by Room).<br>
 * @param todo  Description or name of the task.<br>
 * @param date  Due date for the task.<br>
 * @param done  Indicates whether the task is completed or not.
 */
public class Todo {

    @PrimaryKey(autoGenerate = true)
    private final int id;

    @NonNull
    private final String todo;

    @NonNull
    private final Date date;

    private final boolean done;

    public Todo(int id, @NonNull String todo, @NonNull Date date, boolean done) {
        this.id = id;
        this.todo = todo;
        this.date = date;
        this.done = done;
    }

    public int getId() {
        return id;
    }

    @NonNull
    public String getTodo() {
        return todo;
    }

    @NonNull
    public Date getDate() {
        return date;
    }

    public boolean done() {
        return done;
    }
}